# Generated by Django 5.2.11 on 2026-06-21 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_driver'),
        ('vehicle', '0002_enterprise_vehicle_brand_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='vehicle.enterprise'),
        ),
    ]
