# Generated by Django 5.2.11 on 2026-06-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_manager_enterprise'),
        ('vehicle', '0002_enterprise_vehicle_brand_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='enterprise',
        ),
        migrations.AddField(
            model_name='manager',
            name='enterprises',
            field=models.ManyToManyField(related_name='managers', to='vehicle.enterprise'),
        ),
    ]
