# Generated by Django 5.2.11 on 2026-05-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Бренд')),
                ('vehicle_type', models.CharField(max_length=20, verbose_name='Тип')),
                ('number_of_seats', models.PositiveIntegerField(verbose_name='Количество мест')),
                ('tank_capacity', models.PositiveIntegerField(verbose_name='Объем бака')),
            ],
            options={
                'db_table': 'brand',
            },
        ),
    ]
