# Generated by Django 5.2.11 on 2026-06-27 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_enterprise_vehicle_brand_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='vehicle.enterprise'),
        ),
    ]
